# Generated by Django 5.2.8 on 2025-11-10 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (BYN)')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Остаток на складе')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='Акционный товар')),
                ('is_active', models.BooleanField(default=True, verbose_name='В продаже')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zooinfo.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Продажа'), ('RETURN', 'Возврат')], default='SALE', max_length=6, verbose_name='Тип транзакции')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zooinfo.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
