# Generated by Django 5.2.8 on 2025-11-11 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='zooinfo.product', verbose_name='Товар')),
                ('country_of_origin', models.CharField(max_length=100, verbose_name='Производитель')),
                ('shelf_life_days', models.IntegerField(blank=True, null=True, verbose_name='Срок годности')),
            ],
            options={
                'verbose_name': 'Детали товара',
                'verbose_name_plural': 'Детали товаров',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='zooinfo.tag', verbose_name='Теги'),
        ),
    ]
