# Generated by Django 5.2.8 on 2025-11-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooinfo', '0002_productdetail_tag_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='shelf_life_days',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
    ]
